### ISSUE TITLE
How i can free a view of the final estates of actions?

### ISSUE THREAD

**Issue by kenMarquez** [dtx12/AndroidAnimationsActions#4]
Hello I love your library I've just realized that I could not do certain things, how I can free a view of the final states of an animation? and How to change the colors, and how I can stop a forever?

**Comment by dtx12** [comment]
Hi! You may cancel forever animation, for example - `Animator animator = forever(..); -> animator.cancel();`
As for changing colors, you may use `color` animation, it applies to entire view using multiply blend mode. About freeing view from the final states of animation - I'll think about this feature(although you may just use relative animations).
